/* Podcast Corpus web app — vanilla JS, no dependencies.
 * Data: ../dist/podcasts.json (generated by scripts/export.py)
 * Guides: ../podcasts/featured/*.md (rendered with a small built-in markdown renderer)
 */
"use strict";

const REPO = "https://github.com/allengaller/podcast-database";

const CAT_NAMES = {
  ai: "AI / 大模型", business: "商业 / 创业", comedy: "喜剧 / 娱乐",
  culture: "文化 / 访谈", education: "教育 / 知识", finance: "财经 / 投资",
  health: "健康 / 健身", history: "历史", life: "生活 / 成长",
  news: "新闻 / 时政", science: "科学 / 科普", story: "罪案 / 悬疑",
  tech: "科技 / 风投", "true-crime": "真实犯罪",
};

const CAT_HUES = {
  ai: 265, business: 160, comedy: 20, culture: 330, education: 45,
  finance: 200, health: 140, history: 280, life: 95, news: 0,
  science: 190, story: 350, tech: 215, "true-crime": 320,
};

const LINK_LABELS = {
  apple: "Apple Podcasts", spotify: "Spotify", xiaoyuzhou: "小宇宙",
  youtube: "YouTube", website: "官方网站", twitter: "Twitter / X",
};

const GUIDES = [
  { id: "guigu-101", name: "《硅谷 101》", file: "../podcasts/featured/guigu-101.md" },
  { id: "this-week-in-tech", name: "《This Week in Tech》", file: "../podcasts/featured/this-week-in-tech.md" },
];

const state = {
  q: "", lang: "all", cat: "all", deep: "all", sort: "updated",
  entries: [], counts: null, generatedAt: null,
};

/* ---------- helpers ---------- */

const $ = (sel) => document.querySelector(sel);

function esc(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

const isTodo = (v) => !v || String(v).trim().toUpperCase() === "TODO";

function catName(c) { return CAT_NAMES[c] || c; }
function catHue(c) { return CAT_HUES[c] || 210; }

/* ---------- markdown (small subset for featured guides) ---------- */

function mdInline(s) {
  return esc(s)
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (m, text, url) => {
      if (!/^(https?:\/\/|\/|#)/i.test(url)) return `${text}`;
      return `<a href="${url}" target="_blank" rel="noopener">${text}</a>`;
    });
}

function mdToHtml(src) {
  // strip YAML frontmatter
  if (/^---\s*\n/.test(src)) {
    const end = src.indexOf("\n---", 3);
    if (end !== -1) src = src.slice(src.indexOf("\n", end + 1) + 1);
  }
  const lines = src.split(/\r?\n/);
  const out = [];
  let para = [];
  const flush = () => {
    if (para.length) { out.push("<p>" + para.map(mdInline).join("<br>") + "</p>"); para = []; }
  };
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (/^```/.test(line)) {
      flush(); const buf = []; i++;
      while (i < lines.length && !/^```/.test(lines[i])) { buf.push(lines[i]); i++; }
      i++;
      out.push("<pre><code>" + esc(buf.join("\n")) + "</code></pre>");
      continue;
    }
    if (/^\s*$/.test(line)) { flush(); i++; continue; }
    const h = line.match(/^(#{1,4})\s+(.*)/);
    if (h) { flush(); const n = h[1].length; out.push(`<h${n}>${mdInline(h[2])}</h${n}>`); i++; continue; }
    if (/^\s*(-{3,}|\*{3,})\s*$/.test(line)) { flush(); out.push("<hr>"); i++; continue; }
    if (/^\s*\|/.test(line)) {
      flush();
      const rows = [];
      while (i < lines.length && /^\s*\|/.test(lines[i])) { rows.push(lines[i].trim()); i++; }
      const cells = (r) => r.replace(/^\||\|$/g, "").split("|").map((c) => c.trim());
      const parsed = rows.map((r) => ({ c: cells(r), sep: /^\|[\s:|-]+\|?$/.test(r) }));
      const head = parsed.find((r) => !r.sep);
      const body = parsed.slice(parsed.indexOf(head) + 1).filter((r) => !r.sep);
      let t = "<table><thead><tr>" + head.c.map((c) => `<th>${mdInline(c)}</th>`).join("") + "</tr></thead><tbody>";
      for (const r of body) t += "<tr>" + r.c.map((c) => `<td>${mdInline(c)}</td>`).join("") + "</tr>";
      t += "</tbody></table>";
      out.push(t);
      continue;
    }
    if (/^\s*[-*]\s+/.test(line)) {
      flush(); const items = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) { items.push(lines[i].replace(/^\s*[-*]\s+/, "")); i++; }
      out.push("<ul>" + items.map((x) => `<li>${mdInline(x)}</li>`).join("") + "</ul>");
      continue;
    }
    if (/^\s*\d+\.\s+/.test(line)) {
      flush(); const items = [];
      while (i < lines.length && /^\s*\d+\.\s+/.test(lines[i])) { items.push(lines[i].replace(/^\s*\d+\.\s+/, "")); i++; }
      out.push("<ol>" + items.map((x) => `<li>${mdInline(x)}</li>`).join("") + "</ol>");
      continue;
    }
    if (/^\s*>\s?/.test(line)) {
      flush(); const buf = [];
      while (i < lines.length && /^\s*>\s?/.test(lines[i])) { buf.push(lines[i].replace(/^\s*>\s?/, "")); i++; }
      out.push("<blockquote>" + buf.map(mdInline).join("<br>") + "</blockquote>");
      continue;
    }
    para.push(line); i++;
  }
  flush();
  return out.join("\n");
}

/* ---------- stats ---------- */

function renderStats() {
  const c = state.counts;
  $("#stats").innerHTML = [
    ["总档数", c.total], ["深档", c.deep], ["Stub 待补", c.stub],
    ["中文", c.zh], ["英文", c.en], ["数据截至", state.generatedAt],
  ].map(([k, v]) => `<span class="stat"><b>${esc(v)}</b>${esc(k)}</span>`).join("");
}

/* ---------- filters ---------- */

function filtered() {
  const q = state.q.trim().toLowerCase();
  let list = state.entries.filter((e) => {
    if (state.lang !== "all" && e.language !== state.lang) return false;
    if (state.cat !== "all" && e.category !== state.cat) return false;
    if (state.deep === "deep" && !e._deep) return false;
    if (state.deep === "stub" && e._deep) return false;
    if (q) {
      const hay = [e.title, e.slug, e.network, e.category,
        ...(e.hosts || []), ...(e.tags || [])]
        .join(" ").toLowerCase();
      if (!hay.includes(q)) return false;
    }
    return true;
  });
  const zhColl = new Intl.Collator("zh");
  if (state.sort === "updated") {
    list = list.slice().sort((a, b) => String(b.updated_date).localeCompare(String(a.updated_date)));
  } else if (state.sort === "added") {
    list = list.slice().sort((a, b) => String(b.added_date).localeCompare(String(a.added_date)));
  } else {
    list = list.slice().sort((a, b) => zhColl.compare(a.title, b.title));
  }
  return list;
}

function renderCatChips() {
  const pool = state.entries.filter((e) => state.lang === "all" || e.language === state.lang);
  const counts = new Map();
  for (const e of pool) counts.set(e.category, (counts.get(e.category) || 0) + 1);
  const cats = [...counts.keys()].sort((a, b) => counts.get(b) - counts.get(a));
  if (state.cat !== "all" && !counts.has(state.cat)) state.cat = "all";
  const btn = (val, label, n) =>
    `<button type="button" class="chip${state.cat === val ? " active" : ""}" data-cat="${esc(val)}">` +
    `${esc(label)}<span class="n">${n}</span></button>`;
  $("#catRow").innerHTML =
    btn("all", "全部赛道", pool.length) +
    cats.map((c) => btn(c, catName(c), counts.get(c))).join("");
}

function renderStatusChips() {
  const pool = state.entries.filter((e) =>
    (state.lang === "all" || e.language === state.lang) &&
    (state.cat === "all" || e.category === state.cat));
  const deep = pool.filter((e) => e._deep).length;
  const stub = pool.length - deep;
  const btn = (val, label, n) =>
    `<button type="button" class="chip${state.deep === val ? " active" : ""}" data-deep="${esc(val)}">` +
    `${esc(label)}<span class="n">${n}</span></button>`;
  $("#statusRow").innerHTML =
    btn("all", "全部状态", pool.length) +
    btn("deep", "深档", deep) + btn("stub", "Stub", stub);
}

/* ---------- grid ---------- */

function cardHtml(e) {
  const tags = (e.tags || []).slice(0, 3);
  const hosts = (e.hosts || []).join(" / ");
  return `<article class="card" tabindex="0" role="button" data-slug="${esc(e.slug)}" style="--h:${catHue(e.category)}">
    <div class="meta-top">
      <span class="cat-chip">${esc(catName(e.category))}</span>
      <span class="badge ${e._deep ? "deep" : "stub"}">${e._deep ? "深档" : "STUB"}</span>
    </div>
    <h3>${esc(e.title)}</h3>
    <p class="network">${esc(e.network || "")}</p>
    <p class="hosts">${esc(hosts)}</p>
    <div class="tagrow">${tags.map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div>
    <div class="foot"><span>${esc(e.language === "zh" ? "中文" : "English")}</span><span>更新 ${esc(e.updated_date)}</span></div>
  </article>`;
}

function renderGrid() {
  const list = filtered();
  $("#resultCount").textContent = `共 ${list.length} 档`;
  $("#grid").innerHTML = list.map(cardHtml).join("");
  $("#emptyState").hidden = list.length > 0;
}

function refresh() {
  renderCatChips();
  renderStatusChips();
  renderGrid();
}

/* ---------- detail sheet ---------- */

function openSheet(e) {
  const links = Object.entries(e.subscribe_links || {})
    .filter(([, v]) => !isTodo(v))
    .map(([k, v]) => `<a href="${esc(v)}" target="_blank" rel="noopener">${esc(LINK_LABELS[k] || k)}</a>`);
  if (!isTodo(e.rss)) {
    links.push(`<a href="${esc(e.rss)}" target="_blank" rel="noopener">RSS 订阅</a>`);
  }
  links.push(`<a href="${REPO}/blob/main/${encodeURI(e._path)}" target="_blank" rel="noopener">查看源档案 (GitHub)</a>`);

  $("#sheet").innerHTML = `
    <button type="button" class="sheet-close" aria-label="关闭">✕</button>
    <div class="meta-top" style="--h:${catHue(e.category)}">
      <span class="cat-chip">${esc(catName(e.category))}</span>
      <span class="badge ${e._deep ? "deep" : "stub"}">${e._deep ? "深档" : "STUB"}</span>
      <span class="badge stub">${esc(e.status)}</span>
      <span class="badge stub">${esc(e.language === "zh" ? "中文" : "English")}</span>
    </div>
    <h2>${esc(e.title)}</h2>
    <p class="network-line">${esc(e.network || "")}</p>
    <section><h4>主播 / 团队</h4><ul>${(e.hosts || []).map((h) => `<li>${esc(h)}</li>`).join("")}</ul></section>
    <section><h4>平台</h4><div class="tagrow">${(e.platforms || []).map((p) => `<span class="tag">${esc(p)}</span>`).join("")}</div></section>
    <section><h4>标签</h4><div class="tagrow">${(e.tags || []).map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div></section>
    <section><h4>订阅入口</h4><div class="linklist">${links.join("")}</div></section>
    <section><h4>时间</h4><div class="dates">
      <span>收录 <b>${esc(e.added_date)}</b></span><span>更新 <b>${esc(e.updated_date)}</b></span>
    </div></section>`;
  $("#sheet").hidden = false;
  $("#scrim").hidden = false;
  requestAnimationFrame(() => {
    $("#sheet").classList.add("show");
    $("#scrim").classList.add("show");
  });
}

function closeSheet() {
  $("#sheet").classList.remove("show");
  $("#scrim").classList.remove("show");
  setTimeout(() => { $("#sheet").hidden = true; $("#scrim").hidden = true; }, 220);
}

/* ---------- tabs / featured guides ---------- */

function switchTab(tab) {
  document.querySelectorAll("#tabs .tab").forEach((b) =>
    b.classList.toggle("active", b.dataset.tab === tab));
  $("#view-browse").hidden = tab !== "browse";
  $("#view-featured").hidden = tab !== "featured";
  if (tab === "featured") loadGuide(currentGuideId());
}

function currentGuideId() {
  const m = location.hash.match(/^#featured\/([\w-]+)/);
  return m ? m[1] : GUIDES[0].id;
}

async function loadGuide(id) {
  const guide = GUIDES.find((g) => g.id === id) || GUIDES[0];
  if (location.hash !== `#featured/${guide.id}`) location.hash = `#featured/${guide.id}`;
  $("#guideNav").innerHTML = GUIDES.map((g) =>
    `<button type="button" class="chip${g.id === guide.id ? " active" : ""}" data-guide="${esc(g.id)}">${esc(g.name)}</button>`
  ).join("");
  const body = $("#guideBody");
  body.innerHTML = `<p class="guide-loading">加载专题中…</p>`;
  try {
    const res = await fetch(guide.file);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    body.innerHTML = mdToHtml(await res.text());
  } catch (err) {
    body.innerHTML = `<p class="guide-loading">加载失败(${esc(err.message)})。
      若通过 file:// 打开,请改用本地静态服务:<code>python3 -m http.server</code>。
      也可在 GitHub 阅读:<a href="${REPO}/blob/main/podcasts/featured/${esc(guide.id)}.md" target="_blank" rel="noopener">${esc(guide.name)}</a></p>`;
  }
}

/* ---------- events ---------- */

function bindEvents() {
  $("#tabs").addEventListener("click", (ev) => {
    const b = ev.target.closest(".tab");
    if (b) {
      location.hash = b.dataset.tab === "browse" ? "#browse" : "#featured";
      switchTab(b.dataset.tab);
    }
  });

  $("#langSeg").addEventListener("click", (ev) => {
    const b = ev.target.closest("button[data-lang]");
    if (!b) return;
    state.lang = b.dataset.lang;
    document.querySelectorAll("#langSeg button").forEach((x) =>
      x.classList.toggle("active", x === b));
    refresh();
  });

  $("#catRow").addEventListener("click", (ev) => {
    const b = ev.target.closest("button[data-cat]");
    if (!b) return;
    state.cat = b.dataset.cat;
    refresh();
  });

  $("#statusRow").addEventListener("click", (ev) => {
    const b = ev.target.closest("button[data-deep]");
    if (!b) return;
    state.deep = b.dataset.deep;
    refresh();
  });

  $("#sort").addEventListener("change", (ev) => { state.sort = ev.target.value; renderGrid(); });

  $("#search").addEventListener("input", (ev) => { state.q = ev.target.value; renderGrid(); });

  document.addEventListener("keydown", (ev) => {
    if (ev.key === "/" && document.activeElement !== $("#search")) {
      ev.preventDefault(); $("#search").focus();
    }
    if (ev.key === "Escape" && !$("#sheet").hidden) closeSheet();
  });

  $("#grid").addEventListener("click", (ev) => {
    const card = ev.target.closest(".card");
    if (!card) return;
    const entry = state.entries.find((e) => e.slug === card.dataset.slug);
    if (entry) openSheet(entry);
  });
  $("#grid").addEventListener("keydown", (ev) => {
    if (ev.key !== "Enter" && ev.key !== " ") return;
    const card = ev.target.closest(".card");
    if (!card) return;
    ev.preventDefault();
    const entry = state.entries.find((e) => e.slug === card.dataset.slug);
    if (entry) openSheet(entry);
  });

  $("#scrim").addEventListener("click", closeSheet);
  $("#sheet").addEventListener("click", (ev) => {
    if (ev.target.closest(".sheet-close")) closeSheet();
  });

  $("#guideNav").addEventListener("click", (ev) => {
    const b = ev.target.closest("button[data-guide]");
    if (b) loadGuide(b.dataset.guide);
  });

  window.addEventListener("hashchange", () => {
    const tab = location.hash.startsWith("#featured") ? "featured" : "browse";
    if ($("#view-browse").hidden === (tab === "browse")) switchTab(tab);
    else if (tab === "featured") loadGuide(currentGuideId());
  });
}

/* ---------- boot ---------- */

async function boot() {
  bindEvents();
  const grid = $("#grid");
  try {
    const res = await fetch("../dist/podcasts.json");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    state.entries = data.entries;
    state.counts = data.counts;
    state.generatedAt = data.generated_at;
    renderStats();
    refresh();
  } catch (err) {
    grid.innerHTML = "";
    $("#resultCount").textContent = "";
    $("#emptyState").hidden = false;
    $("#emptyState").innerHTML =
      `<p>数据加载失败(${esc(err.message)})。</p>
       <p>若通过 <code>file://</code> 直接打开,请在仓库根目录运行
       <code>python3 -m http.server</code> 后访问 <code>/web/</code>。</p>`;
  }
  const tab = location.hash.startsWith("#featured") ? "featured" : "browse";
  if (tab === "featured") switchTab("featured");
}

boot();
